### ISSUE TITLE
No version for Julia 1.6.1

### ISSUE THREAD

**Issue by ammonite** [BioJulia/BioSequences.jl#186] opened 2021-10-04 01:47 UTC
add BioSequences get ERROR:
ERROR: Unsatisfiable requirements detected for package BioSequences [7e6ae17a]:
 BioSequences [7e6ae17a] log:
 ├─BioSequences [7e6ae17a] has no known versions!
 └─restricted to versions * by an explicit requirement — no versions left

**Comment by jakobnissen** [comment] 2021-10-04 07:50
Closing as duplicate of #185

**Closed by jakobnissen** 2021-10-04 07:50 UTC
